### ISSUE TITLE
Not Work React Native 0.57.1

### ISSUE THREAD

**Issue by hitaloramon** [flextv/react-native-google-cast#27]
does not work with the newest version of react native 0.57.1

Of the error when trying to compile

Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives

**Comment by petrbela** [comment]
Hmm possibly related to the upgraded Android version in 0.57. We're actually just about to upgrade ourselves so I'll give this a high priority.

**Comment by hitaloramon** [comment]
Have you found a solution to this?

**Comment by petrbela** [comment]
Hey, haven't had time to look into it yet, probably later this week.

**Comment by kay-is** [comment]
I tried getting it to work and found multiple problems.

The merge-error came from too many methods in the `dex` file. So I had to switch the app to multi-dex. Now it builds again.

Then I had to update the play-services-cast-framework from `10.0.1` to `16.1.0` because the app would crash at start. Probably because the new RN version wasn't compatible with the old framework or because some modules I use (`react-native-push-notification`) also used a play-services framework of version 16.

Anyway, this fixed the crash at the start, and I could render the `CastButton` component.

But now it crashes when I press that button. 

    java.lang.IllegalSateException: The activity must be a subclass of FragmentActivity at android.support.v7.app.MediaRouteButton.java

This exception is thrown inside Google source, so I think `react-native-google-cast` is simply using the wrong version of `MediaRouteButton` the new one, for API version 16, is in `android.app.MediaRouteButton`

But the class changed so much, that I get many errors about overriding non-existant methods or wrong types in method calls etc.

So I'm giving up for today.

**Comment by owenjeon** [comment]
Same error.

**Comment by padampadam** [comment]
Same here

**Comment by petrbela** [comment]
Hi all. Sorry it's been taking so long. I'm finally finishing a rewrite of the library with all the latest features and dependencies. It supports iOS SDK v4, Android v16, RN 0.57, and also tentative support for react-native-web in Chrome.

It will be released sometime ~next week~ soon. I'll try to add a fix for the current master in the meantime.

**Comment by petrbela** [comment]
V3 has been released https://github.com/react-native-google-cast/react-native-google-cast

Now onto V4!
