### ISSUE TITLE
"MyApp has stopped error" when launching on android.

### ISSUE THREAD

**Issue by aecorredor** [flextv/react-native-google-cast#6]
Right after installing the package and following the installation instruction the app crashes right after launch. Have you ever encountered this? Any thoughts on what it might be?

**Comment by petrbela** [comment]
Please make sure you get the package from Github because there's still an old version on npm. This is what you should have in package.json:

```js
"react-native-google-cast": "flextv/react-native-google-cast"
```

We'll be merging this project into the original repo and publishing a new version on npm soon but in the meantime, it's a bit more complicated.

**Comment by aecorredor** [comment]
@petrbela thanks for the quick response! Yeap, I made sure that's the one I'm getting. It still crashes on launch. I had a working build and right after installing the package the crash started happening. Maybe there are some steps missing from the Github installation instructions?

**Comment by petrbela** [comment]
Can you look into the Xcode/AndroidStudio console (or turn on RN debugger) to see what the error exactly is?

**Comment by aecorredor** [comment]
The thing is I can't even turn on the RN debugger the usual way because the app crashes right on launch. I don't get anything in the android console either. I'm trying to figure it out, I'll post any updates.

**Comment by aecorredor** [comment]
@petrbela so I actually tried running it on iOS (before I only tried android) and it worked fine. It rendered the `CastButton` and connected successfully. So it's just breaking on android.

**Comment by petrbela** [comment]
Ok, I'll have to check Android. What version of React Native are you using?

**Comment by aecorredor** [comment]
@petrbela perfect, the version we're using is `"react-native": "^0.55.2"`. Let me know if you're able to get it running on an android phone. Also, I ended up here because when using the original version by charliesbox, I couldn't get devices on android, basically I got that there were devices around but the list was always empty. Did you ever find a solution for this when using the v2 version of the chromecast sdk?

**Comment by petrbela** [comment]
@jedashford is using this library on Android with RN 0.55 so he might have some idea. I might have some time to check back on it over the weekend.

We had some major issues with the v2 SDK which is why we wrote the v3 library. Instead of investigating what's wrong with v2, I'd suggest you try to get v3 work (we're planning to merge this back with @charliesbox's repo and support in the future).

**Comment by aecorredor** [comment]
@petrbela ok man, I really appreciate the help. Yeah I'm done trying to get the v2 to work. I'll keep trying with your fork and let you know if anything. Maybe @jedashford can let me know if I'm missing some step for android that's not in the readme?

Thank you both.

**Comment by jedashford** [comment]
I'm confident you can get it working as we have by just following the instructions. You should be able to see the logs and find the crash using logcat in android studio. If you select your emulator or device on the logcat tab, you'll see the big red stacktraces with details on whats failing.

I'd suggest a few things:
1. Try to roll back to before you made an install of the library and make sure to run these in place of the instructions for these steps in the readme:
`$ npm install github:flextv/react-native-google-cast --save`
`$ react-native link react-native-google-cast`

**Comment by aecorredor** [comment]
@jedashford I was able to see the error on app crash with logcat:

 ```
--------- beginning of crash
06-29 04:06:59.781 4239-4239/com.APP_NAME E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.APP_NAME, PID: 4239
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/internal/zzac;
        at com.google.android.gms.internal.zzyu.<init>(Unknown Source)
        at com.google.android.gms.internal.zzyu.<init>(Unknown Source)
        at com.google.android.gms.cast.framework.CastContext.<clinit>(Unknown Source)
        at com.facebook.react.GoogleCastActivity.onCreate(GoogleCastActivity.java:57)
        at com.APP_NAME.MainActivity.onCreate(MainActivity.java:34)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.internal.zzac" on path: DexPathList[[zip file "/data/app/com.APP_NAME-1/base.apk"],nativeLibraryDirectories=[/data/app/com.APP_NAME-1/lib/x86, /data/app/com.APP_NAME-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.android.gms.internal.zzyu.<init>(Unknown Source) 
        at com.google.android.gms.internal.zzyu.<init>(Unknown Source) 
        at com.google.android.gms.cast.framework.CastContext.<clinit>(Unknown Source) 
        at com.facebook.react.GoogleCastActivity.onCreate(GoogleCastActivity.java:57) 
        at com.APP_NAME.MainActivity.onCreate(MainActivity.java:34) 
        at android.app.Activity.performCreate(Activity.java:6237) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.internal.zzac
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 18 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```
I'm trying to debug now, I'm thinking it could be related to the step where we have to manually add the GoogleCast context to Activity.

**Comment by aecorredor** [comment]
@petrbela no luck yet. I followed the troubleshooting steps and made sure both the emulator and the actual device where I'm testing have google play services installed. Still same issue. I'll keep at it and update this once I figure it out.

**Comment by aecorredor** [comment]
@jedashford did you have to add ```classpath 'com.google.gms:google-services:3.2.1'``` to your build.grade?

**Comment by jedashford** [comment]
/build.gradle:
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'com.google.gms:google-services:3.2.1'
        classpath 'io.fabric.tools:gradle:1.25.4'
        classpath 'com.google.firebase:firebase-plugins:1.1.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}
`

Important bits from app/build.grade:

`apply plugin: "com.android.application"
apply plugin: "io.fabric"
apply plugin: "com.google.firebase.firebase-perf"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }



    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-google-signin')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:mediarouter-v7:27.1.1'
    implementation 'com.google.android.gms:play-services-cast-framework:15.0.1'
    compile 'com.android.support:appcompat-v7:27.1.1'
    compile 'com.android.support:mediarouter-v7:27.1.1'
    compile project(':react-native-google-cast')
    compile project(':react-native-video')
    compile project(':react-native-vector-icons')
    compile project(':react-native-orientation')
    compile project(':react-native-keep-awake')
    compile(project(':react-native-firebase')) {
        transitive = false
    }
    compile project(':react-native-fbsdk')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.facebook.react:react-native:+"

    implementation(project(":react-native-google-signin")){
        exclude group: "com.google.android.gms" // very important
    }

    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation "com.google.firebase:firebase-core:15.0.2"
    // For animated GIF support
    implementation 'com.facebook.fresco:animated-gif:1.3.0'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true
    }
    implementation "com.google.firebase:firebase-messaging:15.0.2"
    implementation 'me.leolin:ShortcutBadger:1.1.21@aar' // <-- Add this line if you wish to use badge on Android
    implementation "com.google.firebase:firebase-analytics:15.0.2"
    implementation "com.google.firebase:firebase-perf:15.1.0"


}

// Run this once to be able to run the application with BUCK
// puts all implementation dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.implementation
    into 'libs'
}

apply plugin: 'com.google.gms.google-services'`

**Comment by aecorredor** [comment]
@jedashford awesome dude, I got it running on android. I think I just needed to include ```compile "com.google.android.gms:play-services-base:15.0.0"```. Now I'm getting a runtime error: ```Error while updating property 'tintColor' of a view managed by: RNGoogleCastButton```

**Comment by jedashford** [comment]
You can either remove the tint color or pull in my fork which has the fix for the tintColor: https://github.com/jedashford/react-native-google-signin

**Comment by aecorredor** [comment]
@jedashford you da man
